### ISSUE TITLE
Set up repository with DevOps stuff

### ISSUE THREAD

**Issue by janiskemper** [SovereignCloudStack/csctl-plugin-openstack#1]
## Description

We want the csctl-plugin-openstack to be a binary that is built based on go code in this repository. We therefore want to have everything related to linting Go, build pipelines and methods (based on a main.go in root directory), releasing, and everything else to automate things.

Please make a list of what you included and ask if there are doubts about how this should look like.

**Comment by kranurag7** [comment]
I think this is done now, we can close this now.
