### ISSUE TITLE
Fix failing "Verify Pull Request" job in Github actions

### ISSUE THREAD

**Issue by michal-gubricky** [SovereignCloudStack/csctl-plugin-openstack#8]
/kind bug

**What steps did you take and what happened:**
We are unable to generate token, cause of this error: `Error: secretOrPrivateKey must be an asymmetric key when using RS256
`. See [failing job](https://github.com/SovereignCloudStack/csctl-plugin-openstack/actions/runs/8627782823/job/23648427638?pr=4).

**Comment by jschoone** [comment]
Hi @michal-gubricky, seems like it's fixed, so I gonna close this.
The error at https://github.com/SovereignCloudStack/csctl-plugin-openstack/actions/runs/9305327244/job/25611981921?pr=16 has another reason.

**Comment by michal-gubricky** [comment]
> Hi @michal-gubricky, seems like it's fixed, so I gonna close this. The error at https://github.com/SovereignCloudStack/csctl-plugin-openstack/actions/runs/9305327244/job/25611981921?pr=16 has another reason.

Great, thank you. Yeah, it seems like. I will create an issue for that and later on, I will take a look at it.
